### ISSUE TITLE
Test Adapter error - "Could not start Karma"

### ISSUE THREAD

**Issue by colindembovsky** [MortenHoustonLudvigsen/KarmaTestAdapter#29]
Hi Morten

I've updated to the latest version of your test adapter - however, when VS does test discovery, I get the following error:

```
[Karma] [Error] [Nwc.Web] Could not start Karma
The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at TwoPS.Processes.Process.Run()
   at TwoPS.Processes.ProcessRunner.Run(ProcessRunnerOptions options)
   at NpmProxy.Npm.Root(Boolean global) in c:\Git\JsTestAdapter\NpmProxy\Commands\Root.cs:line 18
   at JsTestAdapter.TestServerClient.TestServer.<GetNodePath>d__2.MoveNext() in c:\Git\JsTestAdapter\JsTestAdapter\TestServerClient\TestServer.cs:line 45
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at JsTestAdapter.TestServerClient.TestServer.get_NodePath() in c:\Git\JsTestAdapter\JsTestAdapter\TestServerClient\TestServer.cs:line 31
   at JsTestAdapter.TestServerClient.TestServer.GetProcessOptions() in c:\Git\JsTestAdapter\JsTestAdapter\TestServerClient\TestServer.cs:line 79
   at JsTestAdapter.TestServerClient.TestServer.StartServer(Int32 timeout) in c:\Git\JsTestAdapter\JsTestAdapter\TestServerClient\TestServer.cs:line 143
   at JsTestAdapter.TestAdapter.TestContainer.StartTestServer() in c:\Git\JsTestAdapter\JsTestAdapter\TestAdapter\TestContainer.cs:line 163
```

I can run the tests successfully from the command line using ```karma start``` (so karma does exist!). I only have a ```karma.conf.js``` (no ```KarmaTestAdapter.json```).

**Comment by MortenHoustonLudvigsen** [comment]
Hi Colin

I'm sorry to hear that it isn't working for you. Can you tell me whether you have node.exe in your path?

**Comment by colindembovsky** [comment]
Wow that was a quick response! My node.exe is located in my chocolatey bin folder:
```C:\Users\All Users\chocolatey\bin```

**Comment by MortenHoustonLudvigsen** [comment]
Is that in your PATH environment variable?

**Comment by colindembovsky** [comment]
Yes, both paths are in my PATH environment variable. I can run node from any command window.

**Comment by MortenHoustonLudvigsen** [comment]
No easy solution then :smile:

I think the first thing I need to do is to improve the "discovery" of node.exe, and have better logging of missing files. I will get back to you as soon as I have implemented that.

**Comment by colindembovsky** [comment]
Thanks Morten!

**Comment by MortenHoustonLudvigsen** [comment]
@colindembovsky I have made a prerelease ([v1.1.1-alpha1](https://github.com/MortenHoustonLudvigsen/KarmaTestAdapter/releases/tag/v1.1.1-alpha1)). I am hopeful, that it will resolve this issue. If not, at least it should provide better logging.
Would you be able to give it a spin?

**Comment by colindembovsky** [comment]
@MortenHoustonLudvigsen I've installed the alpha build - the logging showed all the paths where your extension is looking for ```npm.cmd``` (not ```node.exe```). My npm.cmd file is in this directory:
```C:\ProgramData\chocolatey\lib\npm.1.4.9\tools``` folder. When I added that to my ```PATH``` the extension started working again.

Thanks for the help and quick turnaround!

**Comment by MortenHoustonLudvigsen** [comment]
@colindembovsky Great! I will make it a full release then. By the way, it will only log directories it looks for `node.exe` or `npm.cmd` if it can not find the file. So it is by design, that i doesn't show paths for `node.exe`.
