### ISSUE TITLE
VS 2015 Community after updating to Update 1 doesn't discover any test

### ISSUE THREAD

**Issue by zalayeto** [MortenHoustonLudvigsen/KarmaTestAdapter#50]
Someone else having the same issue?

I can see this error in the test output.

[Karma] [Error] [###########] [Server] Server error
Cannot process request because the process (11928) has exited.
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.Kill()
   at TwoPS.Processes.Process.Run()
   at JsTestAdapter.TestServerClient.TestServer.<StartServer>b__1a() in c:\Git\JsTestAdapter\JsTestAdapter\TestServerClient\TestServer.cs:line 188

Thanks.

**Comment by ivan-karlovich** [comment]
The same issue.
