### ISSUE TITLE
TypeError: logger.setLevel is not a function

### ISSUE THREAD

**Issue by jfineman** [MortenHoustonLudvigsen/KarmaTestAdapter#63]
I'm using Visual Studio 2015 and Update 3

[Karma] [Error] [Startracks.Web/Scripts/angularjs] \Scripts\angularjs\node_modules\karma\lib\logger.js:103
[Karma] [Error] [Startracks.Web/Scripts/angularjs]     logger.setLevel(level)
[Karma] [Error] [Startracks.Web/Scripts/angularjs]            ^
[Karma] [Error] [Startracks.Web/Scripts/angularjs] TypeError: logger.setLevel is not a function
[Karma] [Error] [Startracks.Web/Scripts/angularjs]     at Object.create (c:\Scripts\angularjs\node_modules\karma\lib\logger.js:103:12)
[Karma] [Error] [Startracks.Web/Scripts/angularjs]     at Object.<anonymous> (APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\EUQ3VHAD.CKU\KarmaTestServer\GlobalLog.ts:15:33)
[Karma] [Error] [Startracks.Web/Scripts/angularjs]     at Module._compile (module.js:570:32)
[Karma] [Error] [Startracks.Web/Scripts/angularjs]     at Object.Module._extensions..js (module.js:579:10)
[Karma] [Error] [Startracks.Web/Scripts/angularjs]     at Module.load (module.js:487:32)
[Karma] [Error] [Startracks.Web/Scripts/angularjs]     at tryModuleLoad (module.js:446:12)
[Karma] [Error] [Startracks.Web/Scripts/angularjs]     at Function.Module._load (module.js:438:3)
[Karma] [Error] [Startracks.Web/Scripts/angularjs]     at Module.require (module.js:497:17)
[Karma] [Error] [Startracks.Web/Scripts/angularjs]     at require (internal/module.js:20:19)
[Karma] [Error] [Startracks.Web/Scripts/angularjs]     at Object.<anonymous> (APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\EUQ3VHAD.CKU\KarmaTestServer\Start.ts:1:17)
[Karma] [Error] [Startracks.Web/Scripts/angularjs]     at Module._compile (module.js:570:32)
[Karma] [Error] [Startracks.Web/Scripts/angularjs]     at Object.Module._extensions..js (module.js:579:10)
[Karma] [Error] [Startracks.Web/Scripts/angularjs]     at Module.load (module.js:487:32)
[Karma] [Error] [Startracks.Web/Scripts/angularjs]     at tryModuleLoad (module.js:446:12)
[Karma] [Error] [Startracks.Web/Scripts/angularjs]     at Function.Module._load (module.js:438:3)
[Karma] [Error] [Startracks.Web/Scripts/angularjs]     at Module.runMain (module.js:604:10)
[Karma] [Warning] [Startracks.Web/Scripts/angularjs] Karma stopped - exit code: 1
[Karma] [Warning] [Startracks.Web/Scripts/angularjs] Restarting Karma

**Comment by BlackJair** [comment]
I'm facing the same problem, any suggestions?
